# Generated by Django 5.2.13 on 2026-05-05 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('file_name', models.CharField(max_length=500)),
                ('file_type', models.CharField(max_length=100)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BugType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigFieldType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ElementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('code_prefix', models.CharField(blank=True, max_length=10)),
                ('build_versions', models.JSONField(default=list)),
                ('current_build_version', models.CharField(blank=True, default='', max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PlanIncludes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RunEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_result_snapshot', models.TextField(blank=True, default='')),
                ('steps_snapshot', models.JSONField(default=list)),
                ('element_purpose_snapshot', models.JSONField(default=list)),
                ('element_precondition_snapshot', models.TextField(blank=True, default='')),
                ('actual_result', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('Untouched', 'Untouched'), ('Pass', 'Pass'), ('Fail', 'Fail'), ('Blocked', 'Blocked'), ('Skip', 'Skip')], default='Untouched', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('time_taken_sec', models.PositiveIntegerField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('added_during_run', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('is_exploratory', models.BooleanField(default=False)),
                ('build_version_snapshot', models.CharField(blank=True, default='', max_length=100)),
                ('summary', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('steps', models.JSONField(default=list)),
                ('before_description', models.TextField(blank=True, default='')),
                ('after_description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('New', 'New'), ('Open', 'Open'), ('In Progress', 'In Progress'), ('Fixed', 'Fixed'), ('Verified', 'Verified'), ('Closed', 'Closed'), ("Won't Fix", "Won't Fix")], default='New', max_length=20)),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20)),
                ('priority', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20)),
                ('reproducibility', models.CharField(choices=[('Always', 'Always'), ('Sometimes', 'Sometimes'), ('Rarely', 'Rarely'), ('Once', 'Once'), ('Cannot Reproduce', 'Cannot Reproduce')], default='Always', max_length=30)),
                ('also_affects', models.JSONField(default=list)),
                ('linked_tc_codes', models.JSONField(default=list)),
                ('reporter', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('after_attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_after', to='api.attachment')),
                ('before_attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_before', to='api.attachment')),
                ('bug_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bugs', to='api.bugtype')),
            ],
        ),
        migrations.AddField(
            model_name='attachment',
            name='bug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.bug'),
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('purpose', models.JSONField(default=list)),
                ('precondition', models.TextField(blank=True, default='')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='api.element')),
                ('element_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elements', to='api.elementtype')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='api.game')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='bug',
            name='element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bugs', to='api.element'),
        ),
        migrations.AddField(
            model_name='elementtype',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_types', to='api.game'),
        ),
        migrations.AddField(
            model_name='bugtype',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_types', to='api.game'),
        ),
        migrations.AddField(
            model_name='bug',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='api.game'),
        ),
        migrations.CreateModel(
            name='GameConfigField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('group_label', models.CharField(blank=True, default='', max_length=100)),
                ('field_type', models.CharField(max_length=50)),
                ('default_value', models.TextField(blank=True, default='')),
                ('constraints', models.JSONField(blank=True, default=dict)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_fields', to='api.game')),
            ],
            options={
                'ordering': ['order_index', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='api.genre'),
        ),
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='api.platform'),
        ),
        migrations.CreateModel(
            name='RelationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_types', to='api.game')),
            ],
            options={
                'unique_together': {('game', 'name')},
            },
        ),
        migrations.AddField(
            model_name='bug',
            name='run_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bugs', to='api.runentry'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='run_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.runentry'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='api.game')),
            ],
            options={
                'unique_together': {('game', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('priority', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20)),
                ('precondition', models.TextField(blank=True, default='')),
                ('steps', models.JSONField(default=list)),
                ('expected_result', models.TextField()),
                ('is_regression', models.BooleanField(default=False)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_cases', to='api.element')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='api.game')),
                ('source_bug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_test_cases', to='api.bug')),
            ],
            options={
                'ordering': ['order_index', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='runentry',
            name='test_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='run_entries', to='api.testcase'),
        ),
        migrations.CreateModel(
            name='PlanIncludeExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excluded_element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_exclusions', to='api.element')),
                ('inclusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='api.planincludes')),
                ('excluded_tc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_exclusions', to='api.testcase')),
            ],
        ),
        migrations.AddField(
            model_name='bug',
            name='source_tc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourced_bugs', to='api.testcase'),
        ),
        migrations.CreateModel(
            name='TestCaseTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tag')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.testcase')),
            ],
            options={
                'unique_together': {('test_case', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='testcase',
            name='tags',
            field=models.ManyToManyField(blank=True, through='api.TestCaseTag', to='api.tag'),
        ),
        migrations.CreateModel(
            name='TestCaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tc_types', to='api.game')),
            ],
            options={
                'unique_together': {('game', 'name')},
            },
        ),
        migrations.AddField(
            model_name='testcase',
            name='tc_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_cases', to='api.testcasetype'),
        ),
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, default='', max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_plans', to='api.game')),
            ],
        ),
        migrations.AddField(
            model_name='testcase',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scoped_test_cases', to='api.testplan'),
        ),
        migrations.AddField(
            model_name='planincludes',
            name='child_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='included_in_plans', to='api.testplan'),
        ),
        migrations.AddField(
            model_name='planincludes',
            name='parent_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='included_plans', to='api.testplan'),
        ),
        migrations.AddField(
            model_name='bug',
            name='source_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourced_bugs', to='api.testplan'),
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('build_version_snapshot', models.CharField(max_length=100)),
                ('game_config_snapshot', models.JSONField(default=dict)),
                ('tc_order_snapshot', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Complete', 'Complete'), ('Abandoned', 'Abandoned')], default='In Progress', max_length=20)),
                ('tester_name', models.CharField(max_length=150)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='api.game')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_runs', to='api.testplan')),
            ],
        ),
        migrations.AddField(
            model_name='runentry',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='api.testrun'),
        ),
        migrations.AddField(
            model_name='bug',
            name='test_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bugs', to='api.testrun'),
        ),
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('Run Started', 'Run Started'), ('TC Opened', 'TC Opened'), ('TC Result Submitted', 'TC Result Submitted'), ('Bug Filed', 'Bug Filed'), ('TC Created During Run', 'TC Created During Run'), ('TC Linked to Bug', 'TC Linked to Bug'), ('Run Completed', 'Run Completed'), ('Run Abandoned', 'Run Abandoned')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('detail', models.JSONField(default=dict)),
                ('tester', models.CharField(max_length=150)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='api.testrun')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='elementtype',
            unique_together={('game', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='bugtype',
            unique_together={('game', 'name')},
        ),
        migrations.CreateModel(
            name='RelatedElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_elements', to='api.element')),
                ('target_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referenced_by', to='api.element')),
                ('relation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.relationtype')),
            ],
            options={
                'unique_together': {('element', 'target_element', 'relation_type')},
            },
        ),
        migrations.CreateModel(
            name='PlanTC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_tcs', to='api.testcase')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_tcs', to='api.testplan')),
            ],
            options={
                'ordering': ['order_index'],
                'unique_together': {('plan', 'test_case')},
            },
        ),
        migrations.CreateModel(
            name='PlanItemTC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_item_tcs', to='api.element')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_item_tcs', to='api.testcase')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_item_tcs', to='api.testplan')),
            ],
            options={
                'ordering': ['order_index'],
                'unique_together': {('plan', 'element', 'test_case')},
            },
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='api.element')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='api.testplan')),
            ],
            options={
                'ordering': ['order_index'],
                'unique_together': {('plan', 'element')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='planincludes',
            unique_together={('parent_plan', 'child_plan')},
        ),
        migrations.CreateModel(
            name='PlanConfigValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('config_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_values', to='api.gameconfigfield')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_values', to='api.testplan')),
            ],
            options={
                'unique_together': {('plan', 'config_field')},
            },
        ),
    ]
